import { Inter } from 'next/font/google'
import TopNav from '@/components/TopNav'
import Footer from '@/components/Footer'
import styles from './layout.module.css'
const inter = Inter({ subsets: ['latin'] })

// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <TopNav />
            <main className={`${inter.className} ${styles.main}`}>
                {children}
            </main>
            <Footer />
        </>
    )
}
